version: 2.1
jobs:
  build:
    working_directory: ~/ngx-ethereum-workspace
    docker:
      - image: cimg/node:16.16-browsers
    steps:
      - checkout
      - restore_cache:
          key: ngx-ethereum-workspace-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: ngx-ethereum-workspace-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI
