version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  build:
    working_directory: ~/ngx-ethereum-workspace
    docker:
      - image: cimg/node:16.16-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          key: ngx-ethereum-workspace-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: ngx-ethereum-workspace-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: CHROME_BIN=/usr/bin/google-chrome yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI
