version: 2.1
jobs:
  build:
    working_directory: ~/ngx-ethereum-workspace
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - restore_cache:
          key: ngx-ethereum-workspace-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          key: ngx-ethereum-workspace-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: yarn run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
